server:
  port: 8081

spring:
  application:
    name: user-service

  jpa:
    hibernate:
      ddl-auto: create

  config:
    import: "optional:configserver:http://localhost:8088/"

  cloud:
    config:
      name: bridge
      profile: server

eureka:
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/